name: Deploy TiMe! to GitHub Pages # Il nome della Action

on:
  push:
    branches:
      - master # La action verrà eseguita in caso di push sul branch master del nostro repository

jobs:
  build:
    runs-on: ubuntu-latest # La action verrà eseguita su l'ultima versione di Ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Operazione di checkout standard utile per la CI
        with:
          persist-credentials: false
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1 # Setup di Node utilizzando la action https://github.com/actions/setup-node
        with:
          node-version: "16.x" # Nel nostro caso, utilizziamo la versione 16.x di Node
      - name: Build
        run:
          | # Esecuzione dei comandi di setup e build del progetto Angular, non dimenticando il parametro --base-href nel comando di build!
          npm install -g @angular/cli@14.0.4
          npm install
          npm run build:prod
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2 # Deploy su GitHub Pages utilizzando la action https://github.com/JamesIves/github-pages-deploy-action
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Indichiamo l'accesso token creato per essere autenticati correttamente, prelevandolo dalle Secrets
          BASE_BRANCH: master
          BRANCH: gh-pages # Il branch che contiene il progetto pubblicato sulle GitHub Pages
          FOLDER: dist # Folder dove è stata eseguita la build del nostro progetto Angular
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ secrets.ACCESS_TOKEN }}
